/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=worker-typegen.env --include-runtime=false --env-interface=CloudflareBindings` (hash: ea42107de23f7a99e102621d714dab8d)
interface __BaseEnv_CloudflareBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BOOTSTRAP_TOKEN: string;
	DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
	WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
		durableNamespaces: "Document" | "WorkspaceEvents";
	}
	interface NotesChecksE2eEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		BOOTSTRAP_TOKEN: string;
		DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
		WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "BOOTSTRAP_TOKEN">> {}
}
