/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=worker-typegen.env --include-runtime=false --env-interface=CloudflareBindings` (hash: f1bfcdd0d981738a64403ad0ae102fd7)
interface __BaseEnv_CloudflareBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	OBSERVABILITY: AnalyticsEngineDataset;
	DELIVERY_QUEUE: Queue;
	API_SOURCE_BURST_LIMIT: RateLimit;
	API_SOURCE_MINUTE_LIMIT: RateLimit;
	API_BURST_LIMIT: RateLimit;
	API_MINUTE_LIMIT: RateLimit;
	CLIENT_TELEMETRY_LIMIT: RateLimit;
	CLIENT_TELEMETRY_PREAUTH_LIMIT: RateLimit;
	BROWSER: BrowserRun;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	CHATGPT_CONNECTION_ENABLED: "false";
	EXPANDED_EMBEDS_ENABLED: "false" | "true";
	NOTION_MARKDOWN_WRITES_ENABLED: "false" | "true";
	OFFLINE_EDITING_ENABLED: "false" | "true";
	WORKSPACE_ACTIVITY_ENABLED: "false" | "true";
	SLACK_CHANNEL_VALIDATION_ENABLED: "false";
	SLACK_SHARE_REFRESH_ENABLED: "false";
	SLACK_RICH_DIGESTS_ENABLED: "false";
	SLACK_DIGEST_DEFAULT_TIMEZONE: "America/Los_Angeles";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BOOTSTRAP_TOKEN: string;
	DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
	WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
	NOTES_WORKFLOW: Workflow<Parameters<import("./src/worker/index").NotesJobWorkflow['run']>[0]['payload']>;
	WORKFLOW_INLINE?: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
		durableNamespaces: "Document" | "WorkspaceEvents";
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		OBSERVABILITY: AnalyticsEngineDataset;
		DELIVERY_QUEUE: Queue;
		API_SOURCE_BURST_LIMIT: RateLimit;
		API_SOURCE_MINUTE_LIMIT: RateLimit;
		API_BURST_LIMIT: RateLimit;
		API_MINUTE_LIMIT: RateLimit;
		CLIENT_TELEMETRY_LIMIT: RateLimit;
		CLIENT_TELEMETRY_PREAUTH_LIMIT: RateLimit;
		BROWSER: BrowserRun;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		CHATGPT_CONNECTION_ENABLED: "false";
		EXPANDED_EMBEDS_ENABLED: "false";
		NOTION_MARKDOWN_WRITES_ENABLED: "false";
		OFFLINE_EDITING_ENABLED: "false";
		WORKSPACE_ACTIVITY_ENABLED: "false";
		SLACK_CHANNEL_VALIDATION_ENABLED: "false";
		SLACK_SHARE_REFRESH_ENABLED: "false";
		SLACK_RICH_DIGESTS_ENABLED: "false";
		SLACK_DIGEST_DEFAULT_TIMEZONE: "America/Los_Angeles";
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		BOOTSTRAP_TOKEN: string;
		DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
		WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
		NOTES_WORKFLOW: Workflow<Parameters<import("./src/worker/index").NotesJobWorkflow['run']>[0]['payload']>;
	}
	interface NotesChecksE2eEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		OBSERVABILITY: AnalyticsEngineDataset;
		DELIVERY_QUEUE: Queue;
		API_SOURCE_BURST_LIMIT: RateLimit;
		API_SOURCE_MINUTE_LIMIT: RateLimit;
		API_BURST_LIMIT: RateLimit;
		API_MINUTE_LIMIT: RateLimit;
		CLIENT_TELEMETRY_LIMIT: RateLimit;
		CLIENT_TELEMETRY_PREAUTH_LIMIT: RateLimit;
		BROWSER: BrowserRun;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		WORKFLOW_INLINE: "true";
		CHATGPT_CONNECTION_ENABLED: "false";
		EXPANDED_EMBEDS_ENABLED: "true";
		NOTION_MARKDOWN_WRITES_ENABLED: "true";
		OFFLINE_EDITING_ENABLED: "true";
		WORKSPACE_ACTIVITY_ENABLED: "true";
		SLACK_CHANNEL_VALIDATION_ENABLED: "false";
		SLACK_SHARE_REFRESH_ENABLED: "false";
		SLACK_RICH_DIGESTS_ENABLED: "false";
		SLACK_DIGEST_DEFAULT_TIMEZONE: "America/Los_Angeles";
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		BOOTSTRAP_TOKEN: string;
		DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
		WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
		NOTES_WORKFLOW: Workflow<Parameters<import("./src/worker/index").NotesJobWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CHATGPT_CONNECTION_ENABLED" | "EXPANDED_EMBEDS_ENABLED" | "NOTION_MARKDOWN_WRITES_ENABLED" | "OFFLINE_EDITING_ENABLED" | "WORKSPACE_ACTIVITY_ENABLED" | "SLACK_CHANNEL_VALIDATION_ENABLED" | "SLACK_SHARE_REFRESH_ENABLED" | "SLACK_RICH_DIGESTS_ENABLED" | "SLACK_DIGEST_DEFAULT_TIMEZONE" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "BOOTSTRAP_TOKEN" | "WORKFLOW_INLINE">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}