/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=worker-typegen.env --include-runtime=false --env-interface=CloudflareBindings` (hash: a9fd5a8bf210539c955cd32fb2085c4e)
interface __BaseEnv_CloudflareBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	DELIVERY_QUEUE: Queue;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BOOTSTRAP_TOKEN: string;
	DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
	WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
	NOTES_WORKFLOW: Workflow<Parameters<import("./src/worker/index").NotesJobWorkflow['run']>[0]['payload']>;
	WORKFLOW_INLINE?: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
		durableNamespaces: "Document" | "WorkspaceEvents";
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		DELIVERY_QUEUE: Queue;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		BOOTSTRAP_TOKEN: string;
		DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
		WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
		NOTES_WORKFLOW: Workflow<Parameters<import("./src/worker/index").NotesJobWorkflow['run']>[0]['payload']>;
	}
	interface NotesChecksE2eEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		DELIVERY_QUEUE: Queue;
		WORKFLOW_INLINE: "true";
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		BOOTSTRAP_TOKEN: string;
		DOCUMENT: DurableObjectNamespace<import("./src/worker/index").Document>;
		WORKSPACE_EVENTS: DurableObjectNamespace<import("./src/worker/index").WorkspaceEvents>;
		NOTES_WORKFLOW: Workflow<Parameters<import("./src/worker/index").NotesJobWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "BOOTSTRAP_TOKEN" | "WORKFLOW_INLINE">> {}
}
