export const PAGE_MOVE_RECEIPT_VERSION = 1;
export const PAGE_MOVE_RECEIPT_RETENTION_MS = 7 * 24 * 60 * 60_000;
export const PAGE_MOVE_RECEIPT_PRUNE_BATCH_SIZE = 1_000;
export const PAGE_MOVE_RECEIPT_PRUNE_MAX_BATCHES = 10;
